### ISSUE TITLE
Support for automatic gcloud config switching

### ISSUE THREAD

**Issue by JackCA** [binxio/gcp-get-secret#2]
There may be something wrong in my personal setup, but it would be nice if this lib supported [gcloud automatic config switching](https://cloud.google.com/sdk/docs/configurations#automating_configuration_switching).

I'm able to specify the config using the command arg, but it seems to pick up the default profile otherwise.

Either way, looking forward to using this great tool

**Comment by mvanholsteijn** [comment]
Hi @JackCA, thanks for your feedback!

 I dug myself into a hole with respect to backward compatibilty. The intend of this utility is to use it inside a docker container as an entrypoint for resolving secrets. This is why I had the default credentials as the default and gcloud as explicit option.

I changed it so that by default it uses the gcloud option and if gcloud is not on the path, uses the default credentials. the --use-default-credentials can then be specified when using it as container image entry point.

**Comment by mvanholsteijn** [comment]
please let me know if release 0.4.0 does the trick for  you.

**Comment by JackCA** [comment]
That did the trick! Thanks @mvanholsteijn for going above and beyond. I know this use case might have been outside the scope of what you're going for for this lib, but it's a great improvement in my opinion.

I will say, whether you natively support this or not, is that I'm interested in integrating this with [direnv](https://direnv.net/) for my development environment (that doesn't use docker). I imagine defining all of the `gcp://` prefixed values in my `.envrc` and then executing a script based on this library that rewrites all values for the current directory.

For example,

```bash
#.envrc
export SECRET_VALUE=gcp://FOO

# this command looks at all environment variables defined with a gcp value and rewrites them for the duration of the session
gcp-get-secret-rewrite-env 
```

and then in a shell in the directory with that `.envrc`
```
direnv allow
echo $FOO
# output FOOS-SECRET-VALUE
```

This basically avoids needing to run `gcp-get-secret` prior to all commands and is a bit more magical than what's currently going on. I understand that you're targeting docker (and I'm definitely going to use that feature for my docker set up) but I see this as a great ergonomic feature for non-docker local development.

Regardless, you've addressed my current issue so I'll close this. Interested if you have thoughts on the above though.

☮️

**Comment by mvanholsteijn** [comment]
Hi @JackCA,

Good to hear your issue was solved! the functionality you described is easily implemented:

with out additions to the .envrc:
```
gcp-get-secret $SHELL
```

or in the .envrc
```
eval "$(gcp-get-secret env | sed -e 's/^/export /' )"
```

Cheers,

Mark
